name: pipeline

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: build
        run: cargo test --no-run

      - name: test
        run: cargo test --all-features -- --nocapture --quiet

      - name: formatting
        run: cargo fmt --all -- --check

      - name: check
        run: cargo check

      - name: clippy
        run: cargo clippy -- -D warnings

  cargo_publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: check
    name: Publish Cargo Package
    runs-on: ubuntu-latest
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - run: cargo login $CRATES_IO_TOKEN
      - run: cargo publish

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
